spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations:
        - classpath:sql/schema.sql
        - classpath:sql/data.sql

logging:
  level:
    root: INFO
    com.libraryManagementSystem.service: DEBUG
  file:
    name: logs/app.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30

secret:
  key: 1bca93957cba46b0e41f028c907ccdae668a6e16b57e2bda87f9c7af4b6bb133
